import {
  SunSnow,
  Expand,
  Shrink,
  Loader,
  Check,
  Settings,
  TableProperties,
  Milestone,
  Calendar,
  Paintbrush2,
  Trash2,
  XCircle,
  Users,
  ChevronLeft,
  FolderPlus,
} from 'lucide-react'

export const Icons = {
  logo: SunSnow,
  expand: Expand,
  shrink: Shrink,
  loader: Loader,
  check: Check,
  settings: Settings,
  tasks: TableProperties,
  milestone: Milestone,
  calendar: Calendar,
  colors: Paintbrush2,
  trash: Trash2,
  cancell: XCircle,
  users: Users,
  chevronLeft: ChevronLeft,
  addProject: FolderPlus,
}
